"""Se agrega el nuevo campo fecha actualizado, para guardar la fecha de modificaciones a los datos

Revision ID: 012fc38aadb2
Revises: 8f38a6dd90cd
Create Date: 2023-10-24 23:26:35.547104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012fc38aadb2'
down_revision = '8f38a6dd90cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_actualizado', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizado')

    # ### end Alembic commands ###
