"""Se agrega a la base de datos el campo fecha_registro, donde se almacena la fecha en la cual el usuario se registró

Revision ID: 8f38a6dd90cd
Revises: 
Create Date: 2023-10-24 22:58:21.343080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f38a6dd90cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
